In [13]:
import numpy as np
import pandas as pd
from sklearn import datasets

In [14]:
data = datasets.load_diabetes()

In [16]:
data.keys()

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])

In [24]:
df = pd.DataFrame(data=data['data'], columns = data['feature_names'])
df.to_csv('load_diabetes.txt', sep = ',', index = False)

In [26]:
df['target'] = data['target']

In [28]:
df.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  target  
0 -0.002592  0.019907 -0.017646   151.0  
1 -0.039493 -0.068332 -0.092204    75.0  
2 -0.002592  0.002861 -0.025930   141.0  
3  0.034309  0.022688 -0.009362   206.0  
4 -0.002592 -0.031988 -0.046641   135.0

In [136]:
X = df.iloc[:,0:-1]
y = df.iloc[:,-1]
X = np.array(X)
y = np.array(y)

In [137]:
from sklearn.model_selection import train_test_split

In [138]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

In [139]:
from sklearn.linear_model import LinearRegression

In [140]:
lr = LinearRegression()

In [141]:
lr.fit(X_train,y_train)

LinearRegression()

In [142]:
y_pred = lr.predict(X_test)

In [143]:
from sklearn.metrics import r2_score

In [144]:
r2_score(y_test,y_pred)

0.5341988244945842

In [145]:
lr.coef_

array([  -3.88733451, -225.62527795,  517.90438059,  328.31029449,
       -727.20288812,  410.94784789,   80.2547038 ,  218.18152407,
        704.26613704,   40.02330705])

In [146]:
lr.intercept_

152.2555384904859

# My own class of mlr

In [157]:
class MyReg:
    def __init__(self):
        self.slope = None 
        self.intercept = None

    def fit(self,X_train,y_train):
        X_train = np.insert(X_train,0,1,axis = 1)
        betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept = betas[0]
        self.slopes = betas[1:]

    def intercept(self):
        return self.intercept 

    def slopes(self):
        return self.slopes

    def predict(self,X_test):
        return np.dot(X_test,self.slopes) + self.intercept 

In [158]:
my_lr = MyReg()

In [159]:
my_lr.fit(X_train,y_train)

In [160]:
my_lr.slopes

array([  -3.88733451, -225.62527795,  517.90438059,  328.31029449,
       -727.20288812,  410.94784789,   80.2547038 ,  218.18152407,
        704.26613704,   40.02330705])

In [161]:
my_lr.intercept

152.25553849048595

In [162]:
my_lr.predict(X_test)

array([148.09458516, 208.21448655, 186.40135524,  82.48965216,
       163.39653073, 126.18143914, 126.17724958, 264.70331461,
        78.54858451,  73.56481553, 124.4689202 , 142.22687534,
       166.45460816,  98.50324681,  49.71926751, 223.51885186,
       143.44349424, 110.5012214 , 202.53750375,  78.50254776,
       191.80480185, 243.20329918,  75.88567591, 214.90592447,
        55.73373802, 158.02617798, 157.53992794, 158.88760345,
       166.22196789, 107.63395683, 276.82079667, 179.20223753,
        60.48622195, 157.42996282, 218.98051639, 182.29527384,
        70.84294506, 186.74063243, 285.13699146, 196.19271553,
       202.26323537, 145.38409277, 215.03147478, 124.55368149,
        80.17165114,  98.99489648,  82.02540073,  83.40454634,
       289.99417929, 134.33365281, 112.13359083, 152.32232951,
       109.90693735, 226.28507254, 245.73758587,  85.55979881,
       122.28190225, 139.20366172, 198.9567451 , 120.92328732,
       179.99403801, 106.43755487, 123.02826713,  96.45